# Generated by Django 5.1.5 on 2025-01-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_producto_options_producto_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='impuesto',
        ),
    ]
