# Generated by Django 5.1.5 on 2025-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_remove_producto_codigo_remove_producto_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
