# Generated by Django 5.1.5 on 2025-01-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_producto_codigo_producto_impuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='codigoo',
        ),
    ]
