# Generated by Django 5.1.5 on 2025-01-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_producto_codigoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigoo',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='impuesto',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
